steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pmi-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pmi-backend:latest'
      - './backend'
    id: 'build-backend'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/pmi-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pmi-backend'
      - '--image=gcr.io/$PROJECT_ID/pmi-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--cpu=2'
      - '--memory=2Gi'
      - '--timeout=300'
      - '--port=8000'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Build frontend
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run build
    id: 'build-frontend'

  # Deploy frontend to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'frontend/dist/'
      - 'gs://$PROJECT_ID-pmi-frontend/'
    id: 'deploy-frontend'
    waitFor: ['build-frontend']

images:
  - 'gcr.io/$PROJECT_ID/pmi-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/pmi-backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
