# App Engine configuration for backend
runtime: python311

env: standard

instance_class: F2

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.ingestion_service:app --bind :$PORT

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

env_variables:
  ENVIRONMENT: "production"
  PYTHONUNBUFFERED: "1"

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
